version: '3'

services:
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                     MARIADB                         #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
    # mariadb:
    #     build: requirements/mariadb/
    #     image: mariadb
    #     container_name: mariadb
    #     env_file:
    #       - "./.env"
    #     ports:
    #       - "3306:3306"
    #     volumes:
    #       - "/home/idouidi/data/db:/var/lib/mysql"
    #     restart: always
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                     WORDPRESS                       #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
    wordpress:
        # depends_on:
        #   - mariadb
        build: requirements/wordpress/
        container_name: wordpress
        image: wordpress
        env_file:
          - "./.env"
        ports:
          - "9000:9000"
        volumes:
          - "/home/idouidi/data/website:/var/www/"
        tty: true
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                     NGNINX                          #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
    nginx:
        depends_on:
          - wordpress
        build: requirements/nginx/
        container_name: nginx
        image: nginx
        ports:
          - "443:443"
        volumes:
          - "/home/idouidi/data/website:/etc/nginx/sites-available/"
        # networks:
        #   - inception
        tty: true


